using Moq;
using Xunit;
using QuanLyResort.Services;
using QuanLyResort.Models;
using QuanLyResort.Repositories;
using Microsoft.Extensions.Logging;
using QuanLyResort.Data;
using Microsoft.EntityFrameworkCore;

namespace QuanLyResort.Tests.Services
{
    public class BookingServiceTests
    {
        private readonly Mock<IUnitOfWork> _mockUnitOfWork;
        private readonly Mock<INotificationService> _mockNotificationService;
        private readonly Mock<IAuditService> _mockAuditService;
        private readonly Mock<ILogger<BookingService>> _mockLogger;
        private readonly BookingService _bookingService;

        public BookingServiceTests()
        {
            _mockUnitOfWork = new Mock<IUnitOfWork>();
            _mockNotificationService = new Mock<INotificationService>();
            _mockAuditService = new Mock<IAuditService>();
            _mockLogger = new Mock<ILogger<BookingService>>();

            // Setup mock for DbContext using InMemory
            var options = new Microsoft.EntityFrameworkCore.DbContextOptionsBuilder<ResortDbContext>()
                .UseInMemoryDatabase(databaseName: "Test_ResortDb_" + System.Guid.NewGuid().ToString())
                .Options;
            var context = new ResortDbContext(options);
            
            // Seed a RoomType to avoid empty matches in test
            context.RoomTypes.Add(new RoomType { RoomTypeId = 1, TypeName = "Standard Room", TypeCode = "STD" });
            context.SaveChanges();

            _mockUnitOfWork.Setup(u => u.Context).Returns(context);

            // Setup mock for Bookings & Invoices repository
            var mockBookingRepo = new Mock<IRepository<Booking>>();
            var mockInvoiceRepo = new Mock<IRepository<Invoice>>();
            
            _mockUnitOfWork.Setup(u => u.Bookings).Returns(mockBookingRepo.Object);
            _mockUnitOfWork.Setup(u => u.Invoices).Returns(mockInvoiceRepo.Object);
            
            var mockRoomRepo = new Mock<IRepository<Room>>();
            mockRoomRepo.Setup(r => r.FindAsync(It.IsAny<System.Linq.Expressions.Expression<System.Func<Room, bool>>>()))
                .ReturnsAsync(new List<Room>());
            _mockUnitOfWork.Setup(u => u.Rooms).Returns(mockRoomRepo.Object);
            
            // Simulate DbContext assigning an ID when SaveChanges is called
            _mockUnitOfWork.Setup(u => u.SaveChangesAsync())
                .ReturnsAsync(1);

            _bookingService = new BookingService(
                _mockUnitOfWork.Object,
                _mockAuditService.Object,
                _mockNotificationService.Object,
                _mockLogger.Object
            );
        }

        [Fact]
        public async Task CreateBookingAsync_ShouldFormatBookingCodeAndInvoiceNumberCorrectly()
        {
            // Arrange
            var booking = new Booking
            {
                BookingId = 12345, // Simulate ID generated by DB
                CustomerId = 1,
                RoomId = 1,
                CheckInDate = System.DateTime.Now,
                CheckOutDate = System.DateTime.Now.AddDays(2),
                EstimatedTotalAmount = 1000000
            };

            // Setup callback to assign ID to Invoice simulating DB behavior
            _mockUnitOfWork.Setup(u => u.Invoices.AddAsync(It.IsAny<Invoice>()))
                .Callback<Invoice>(inv => inv.InvoiceId = 98765)
                .Returns(Task.CompletedTask);

            // Act
            var result = await _bookingService.CreateBookingAsync(booking, "System");

            // Assert
            Assert.NotNull(result);
            
            // 1. Verify Booking Code formatting (Id = 12345 => BKG0012345)
            Assert.Equal("BKG0012345", result.BookingCode);
            Assert.Equal("Pending", result.Status);
            
            // 2. Verify SaveChangesAsync was called exactly 4 times (Save Booking, Update BookingCode, Save Invoice, Update InvoiceNumber)
            _mockUnitOfWork.Verify(u => u.SaveChangesAsync(), Times.Exactly(4));
        }
    }
}
